// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: appointments.sql

package pg

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAppointment = `-- name: CreateAppointment :one
INSERT INTO appointments (user_id, client_name, appointment_date, start_time, end_time)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, client_name, appointment_date, start_time, end_time, status
`

type CreateAppointmentParams struct {
	UserID          pgtype.Int4 `json:"user_id"`
	ClientName      string      `json:"client_name"`
	AppointmentDate pgtype.Date `json:"appointment_date"`
	StartTime       pgtype.Time `json:"start_time"`
	EndTime         pgtype.Time `json:"end_time"`
}

func (q *Queries) CreateAppointment(ctx context.Context, arg CreateAppointmentParams) (Appointment, error) {
	row := q.db.QueryRow(ctx, createAppointment,
		arg.UserID,
		arg.ClientName,
		arg.AppointmentDate,
		arg.StartTime,
		arg.EndTime,
	)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ClientName,
		&i.AppointmentDate,
		&i.StartTime,
		&i.EndTime,
		&i.Status,
	)
	return i, err
}

const deleteAllAppointments = `-- name: DeleteAllAppointments :exec
DELETE FROM appointments
`

// name of the query that deletes all appointments
func (q *Queries) DeleteAllAppointments(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAllAppointments)
	return err
}

const getAppointmentsForDate = `-- name: GetAppointmentsForDate :many
SELECT id, user_id, client_name, appointment_date, start_time, end_time, status FROM appointments
WHERE user_id = $1 AND appointment_date = $2
`

type GetAppointmentsForDateParams struct {
	UserID          pgtype.Int4 `json:"user_id"`
	AppointmentDate pgtype.Date `json:"appointment_date"`
}

func (q *Queries) GetAppointmentsForDate(ctx context.Context, arg GetAppointmentsForDateParams) ([]Appointment, error) {
	rows, err := q.db.Query(ctx, getAppointmentsForDate, arg.UserID, arg.AppointmentDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Appointment
	for rows.Next() {
		var i Appointment
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ClientName,
			&i.AppointmentDate,
			&i.StartTime,
			&i.EndTime,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
