// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: availability.sql

package pg

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const setAvailability = `-- name: SetAvailability :exec
INSERT INTO availability (
  user_id, day_of_week, start_time, end_time
) VALUES ( $1, $2, $3, $4  )
`

type SetAvailabilityParams struct {
	UserID    pgtype.Int4 `json:"user_id"`
	DayOfWeek int32       `json:"day_of_week"`
	StartTime pgtype.Time `json:"start_time"`
	EndTime   pgtype.Time `json:"end_time"`
}

func (q *Queries) SetAvailability(ctx context.Context, arg SetAvailabilityParams) error {
	_, err := q.db.Exec(ctx, setAvailability,
		arg.UserID,
		arg.DayOfWeek,
		arg.StartTime,
		arg.EndTime,
	)
	return err
}
