// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package pg

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Appointment struct {
	ID              int32       `json:"id"`
	UserID          pgtype.Int4 `json:"user_id"`
	ClientName      string      `json:"client_name"`
	AppointmentDate pgtype.Date `json:"appointment_date"`
	StartTime       pgtype.Time `json:"start_time"`
	EndTime         pgtype.Time `json:"end_time"`
	Status          pgtype.Text `json:"status"`
}

type Availability struct {
	ID        int32       `json:"id"`
	UserID    pgtype.Int4 `json:"user_id"`
	DayOfWeek int32       `json:"day_of_week"`
	StartTime pgtype.Time `json:"start_time"`
	EndTime   pgtype.Time `json:"end_time"`
}

type User struct {
	ID           int32  `json:"id"`
	Name         string `json:"name"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	Slug         string `json:"slug"`
}
